apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-lab-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devops-lab
  template:
    metadata:
      labels:
        app: devops-lab
    spec:
      containers:
      - name: web
        image: shubhbhosa26457614/devops-lab-project:latest
        ports:
        - containerPort: 80
